### ISSUE TITLE
vv create appends to the wrong file

### ISSUE THREAD

**Issue by tomjn** [bradp/vv#342]
The vv create command appends to `vvv-config.yml`, which will cause unstaged changes that prevent a `git pull` to update VVV 2.

Instead these changes should be made to a `vvv-custom.yml` file followed by a reprovision

**Comment by vitolob** [comment]
Whether it is on `vvv-config.yml` or `vvv-custom.yml` appending the site simply does not work. It used to work because it only had the `sites` section. Now it has, by default, two sections, `sites:` and `utilities:`. So when it appends the site it falls under the utilities section, which prevents the new provisioning system from recognizing it as a new site.

The default `vvv.config.yml` now looks like this:
```
---
sites:
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.dev

  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.dev
      - build.wordpress-develop.dev

  #wordpress-trunk: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-trunk.git
  #multisite: https://github.com/Varying-Vagrant-Vagrants/vvv-multisite.git
  #wordpress-meta-environment: https://github.com/WordPress/meta-environment.git

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
```

By the way, I understand a little about the provisioning system thanks to your article. Thank you.
