### ISSUE TITLE
VV doesn't write the hosts section in vvv-custom.yml

### ISSUE THREAD

**Issue by tomjn** [bradp/vv#345]
VV adds the site name such that for a site named `example`, this is added:

```yaml
  example:
```

But it should be writing the hosts here too, e.g.:

```yaml
  example:
    hosts:
      - example.com
```

Adding to `vvv-hosts` in the sites folder is deprecated at the moment, and only supported in VVV2 for legacy reasons
