### ISSUE TITLE
vv list doesn't show sites created with vvv-custom.yml

### ISSUE THREAD

**Issue by ghost** [bradp/vv#349]
After adding this in my vvv-custom.yml, 'vv list' shows only the 4 default sites and doesn't show any other sites created with the following way. I've provisioned and the site works fine. 

```
  website:
   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
   hosts:
     - website.dev
```
